### ISSUE TITLE
Site Nouvelle-Aquitaine affiche toujours l'Ile de France

### ISSUE THREAD

**Issue by OFB-NA** [richaben/PRR_ONDE#10]
Le fichier de configuration a bien été mis à jour pour la Nouvelle-Aquitaine et le lancement des workflows a finalement bien été à son terme mais la page générée affiche toujours l'Ile de France.

**Comment by richaben** [comment]
Il s'agit d'un problème de taille de la page ; cf. cette issue https://github.com/richaben/PRR_ONDE/issues/7
Un allégement des pages est à prévoir

**Comment by richaben** [comment]
Je ferme cette issue. Les modifs proposées par @CedricMondy ont l'air de résoudre le problème. (cf. https://github.com/richaben/PRR_ONDE/pull/12)

**Comment by OFB-NA** [comment]
Le problème avait l'air résolu mais le site NA pointe à nouveau sur l'IdF. 
Avez-vous une idée sur la cause ?

**Comment by OFB-IdF** [comment]
Bonjour,

Le dépôt NA n'a pas été mis à jour ([voir ici](https://github.com/richaben/PRR_ONDE/blob/master/Install.md#mise-%C3%A0-jour-de-loutil) pour la procédure). Une fois que ce sera fait, ça devrait être bon

**Comment by OFB-NA** [comment]
Merci !
J'avais oublié cette étape. C'est bien ça, ça fonctionne.
(Comme la page NA précédemment générée fonctionnait, je pensais que les corrections étaient déjà intégrées.)
