### ISSUE TITLE
lisibilité axe abscisses graphique 

### ISSUE THREAD

**Issue by Josefine57** [richaben/PRR_ONDE#11]
Est-il possible d'améliorer la lisibilité de l'axe des abscisses du premier graphique du bilan régional :
![figureONDE](https://github.com/richaben/PRR_ONDE/assets/128727335/7df3b8c4-8ec9-4716-9651-19f18d6e533a); les chiffres se chevauchent lorsqu'il y a beaucoup de départements sur la figure.

**Comment by OFB-IdF** [comment]
cela devrait pouvoir se régler en n'affichant que les valeurs 0, 50 et 100.

**Comment by richaben** [comment]
Le problème d'affichage est réglé avec la mise à jour a été proposée (PR https://github.com/richaben/PRR_ONDE/pull/15) ; à savoir la création d'un onglet par département, en plus du bilan régional.
