### ISSUE TITLE
ne mettre à jour la page que si de nouvelles données sont disponibles

### ISSUE THREAD

**Issue by OFB-IdF** [richaben/PRR_ONDE#13]
Plutôt que de télécharger les données et régénérer la page html systématiquement tous les jours, il serait mieux de pouvoir vérifier si de nouvelles données disponibles et ne déclencher la mise à jour que si c'est bien le cas.

A voir avec le fonctionnement de hubeau comment on peut faire ça.

**Comment by antonio-andrade** [comment]
C'est possible en utilisant le champ `date_observation` associé aux observations d'écoulement et la fonction de tri des données diffusées :
1. Requêter la date de la dernière observation réalisée dans une région. Exemple avec la région Occitanie :
https://hubeau.eaufrance.fr/api/vbeta/ecoulement/observations?code_region=76&fields=date_observation&format=json&size=1
3. Comparer cette date avec la date la plus récente d'observation  collectée
4. Si besoin, récupérer les observations entre les deux dates. Exemple avec la période 01/01/2023 - 12/05/2023 :
https://hubeau.eaufrance.fr/api/vbeta/ecoulement/observations?format=json&code_region=76&date_observation_min=2023-01-01&date_observation_max=2023-05-12&size=20

**Comment by OFB-IdF** [comment]
ok merci, j'essaierai de regarder ça

**Comment by OFB-IdF** [comment]
Pas encore testé (hubeau n'est pas accessible) mais quelques réflexions pour avoir vos avis.

Si on veut limiter les temps de calcul/transfert de données, une fois la vérification faite de la disponibilité des données faite, il faut donc conditionner le téléchargement des données et les traitements/créations de graphiques à cette disponibilité mais pas la création de la page qui doit refléter via la date qu'une mise à jour a bien eu lieu (sinon on pourrait penser que quelque chose s'est mal passé).

Pour le moment, une partie des traitements est dans le script `01_telechargement_data.R` et l'autre dans le RMarkdown `template.Rmd`. En l'état de mes réflexions sur ce sujet, je pense qu'il faut réorganiser les traitements, voici une proposition:

1. un script de vérification de la disponibilité de nouvelles données qui enregistre une variable précisant si une mise à jour doit être réalisée;
2. un script de téléchargement des données à exécuter si mise à jour nécessaire;
3. un script de préparation des données à exécuter si mise à jour nécessaire;
4. un script de préparation des graphiques et cartes à exécuter si mise à jour nécessaire;
5. un script pour générer le rapport html à exécuter systématiquement.

Les étapes 2, 3 et 4 (au moins les 2 et 3) peuvent aussi se faire dans un seul script ou être exécuté depuis un autre script ne contenant que les commandes permettant de le exécuter.
