### ISSUE TITLE
Basculer vers la version stable de l'API

### ISSUE THREAD

**Issue by antonio-andrade** [richaben/PRR_ONDE#14]
L'API Ecoulement des cours d'eau devrait passer en version stable le 26 mai 2023. Il faudra alors modifier le paramètre *version* utilisé dans les url d'interrogation de l'API.

En pratique, l'url actuelle ...
https://hubeau.eaufrance.fr/api/vbeta/ecoulement/observations?format=json&code_region=76&date_observation_min=2022-01-01&date_observation_max=2022-12-31&size=20

... doit évoluer vers ...
https://hubeau.eaufrance.fr/api/v1/ecoulement/observations?format=json&code_region=76&date_observation_min=2022-01-01&date_observation_max=2022-12-31&size=20

**Comment by CedricMondy** [comment]
Ce sera à prendre en compte dans le package hubeau directement (https://github.com/inrae/hubeau), le souci c'est que la version sur le CRAN ne sera peut-être pas mise à jour rapidement... @PascalIrz tu peux nous en dire plus ?
Si la modif est faite sur la version github du package et qu'il faut un peu de temps avant une disponibilité sur le CRAN, peut-être faudra changer le mode d'installation du package dans l'outil

**Comment by antonio-andrade** [comment]
Il serait intéressant de profiter de cette mise à jour pour injecter le nom du package R Hub'Eau dans le champ d'en-tête http *referer*. Cela permettra l'analyse de l'utilisation du package.

**Comment by antonio-andrade** [comment]
ERRATUM : la date de la bascule est prévue le **23 mai**.

**Comment by OFB-IdF** [comment]
L'idéal serait de pouvoir mettre la version de l'API en paramètre des fonctions du package, cela éviterait d'avoir à adapter le package à chaque changement, juste les scripts qui l'utilisent

**Comment by CedricMondy** [comment]
J'ai regardé un peu le code du package hubeau. Pour faire la mise à jour vers la version stable de l'API il suffirait apparemment de mettre à jour un fichier de config (appelé .cfg dans le package) qui contient pour chaque API le chemin (ce serait le seul élément à changer) et la liste des endpoints. Donc, potentiellement cela peut être très rapide pour eux à modifier, au moins sur la version dev sur GitHub. On n'aurait donc juste à changer l'installation du package depuis github au lieu du CRAN.
J'ai ouvert [une issue à ce sujet](https://github.com/inrae/hubeau/issues/33).

**Comment by OFB-IdF** [comment]
Mes tests ont l'air concluants, j'ai ouvert une PR #27
