### ISSUE TITLE
Problème d'échelle du graphique "Des assecs se suivant d’un mois sur l’autre"

### ISSUE THREAD

**Issue by OFB-NA** [richaben/PRR_ONDE#20]
Pour la Nouvelle-Aquitaine, la modalité "10 mois consécutifs" apparait : 
- les chiffres associés à cette modalité sont visiblement erronés (modalité largement présente chaque année alors que ce cas est très rare)
- la modalité apparait entre "1mois" et "2 mois consécutifs" et non pas après "8 mois consécutifs"
Voyez-vous comment résoudre le problème ?

**Comment by CedricMondy** [comment]
Merci pour le signalement, cela ne devrait effectivement pas arriver puisque normalement on se limite aux campagnes usuelles... Je vais regarder ça.

Tu as vu ça sur [mon test](https://cedricmondy.github.io/PRR_ONDE/), c'est ça ? Aujourd'hui, hubeau n'est pas accessible mais tu peux quand même [mettre à jour ton dépôt](https://github.com/richaben/PRR_ONDE/blob/master/Install.md#mise-%C3%A0-jour-de-loutil), nous avons modifié le code et dès que hubeau sera de nouveau opérationnel, le dépoiement de la page NA depuis votre dépôt devrait pouvoir se faire sans problème.

**Comment by CedricMondy** [comment]
En récupérant les fichiers de chaque région depuis les dépôts correspondants, je trouve que pour NA seulement il y a des doublons, ce qui fausse le calcul du nombre de mois consécutifs (et probablement d'autres aussi). Malheureusement, tant que hubeau n'est pas accessible, je ne peux pas creuser plus.

**Comment by CedricMondy** [comment]
hubeau est revenu, donc j'ai repris les tests.
Le problème semble venir d'une seule station, le Curé à Saint-Georges-du-Bois pour lequel la table stations que l'on récupère a deux lignes identiques, ce qui dédouble toutes les observations de cette station et fausse donc les calculs...
Je ne sais pas exactement d'où vient ce problème, mais on peut forcer la chose en retirant explicitement les doublons

**Comment by OFB-NA** [comment]
Merci pour toutes tes réponses et pour la solution trouvée pour l'affichage de notre page.

En regardant les autres DR, je vois qu'on a aussi des valeurs qui vont jusqu'à 6 mois consécutifs en AURA. On devrait donc partout s'arrêter à 5 si on est sur les usuelles ?

**Comment by CedricMondy** [comment]
Effectivement, pour les campagnes usuelles il ne devrait y avoir au maximum que 5 mois consécutifs en assec. Pour AURA, le problème venait de multiples campagnes enregistrées le même mois. J'ai proposé une modification du code qui devrait résoudre le problème (PR #21)

**Comment by richaben** [comment]
Le doublonnage de données sera à faire remonter à Hub'eau et Onde directement (@antonio-andrade).
Et la PR vient d'être intégrée ! Une nouvelle synchro avec le dépôt de référence est à prévoir.
Merci @OFB-NA & @OFB-IdF .

**Comment by antonio-andrade** [comment]
L'anomalie de doublons de station est rencontrée au niveau des données diffusées par l'API Hub'Eau, et non au niveau des données Onde. J'enregistre un ticket Hub'Eau.
