### ISSUE TITLE
Quels traitements/filtres pour les anciennes stations ?

### ISSUE THREAD

**Issue by richaben** [richaben/PRR_ONDE#26]
Les données des anciennes stations ONDE sont présentes en base, et sont donc affichées sur la page de la carte (cf. exemple) (_et peut-être prises en compte pour les autres traitements_).

![image](https://github.com/richaben/PRR_ONDE/assets/26381994/5bb32a74-607c-4d28-bfbf-ae4acf26dceb)

Vu que dans certaines régions/départements, le réseau de stations a profondément changé, il faut qu'on veille à n'utiliser que les stations actives pour la page.

**Comment by OFB-IdF** [comment]
On doit pouvoir utiliser le champ etat_station dans la table stations.
Pour les graphiques bilans, je suis d'accord il faut les enlever. Pour la carte, je me demande si on ne peut pas les séparer dans une autre couche décochée par défaut pour avoir tout de même la possibilité de les afficher...
