### ISSUE TITLE
Problème mise à jour des données graphs popups 

### ISSUE THREAD

**Issue by richaben** [richaben/PRR_ONDE#29]
@CedricMondy ,
Vu ce matin, sur les copies normandes et idf, les graphiques des popups ne semblent pas être mis à jour avec la donnée récente du mois de mai, alors que les onglets bilans départements et région contiennent bien les données de ce mois.

**Comment by richaben** [comment]
Aujourd'hui, le 27/05, pas d'affichage de la campagne de mai pourtant saisie. 
<img width="450" alt="Capture d’écran 2023-05-27 à 20 58 50" src="https://github.com/richaben/PRR_ONDE/assets/26381994/a85f71b3-7821-454d-8f05-dc8eef312bd2">

Le soucis semble venir de ce filtre (ligne 52 dans le `04_preparer_graphiques`). 

`dplyr::filter(
                  ! (lubridate::as_date(paste0(Annee, "-", as.numeric(Mois) + 1, "-01")) > Sys.Date())
                )`

d'ailleurs le +1 posera peut-être problème au mois de décembre '12' ?

Ceci ne serait pas plus adapté ?

`dplyr::filter(
                  ! (lubridate::as_date(date_campagne) > Sys.Date())
                )`

**Comment by CedricMondy** [comment]
Ok, je regarde !

**Comment by CedricMondy** [comment]
C'est corrigé.
Le truc c'est que les combinaisons stations x année x mois étaient complétées pour visualiser les données manquantes. Mais lorsqu'une nouvelle année de campagne est commencée cette complétion automatique intègre aussi les campagnes à venir et pour que celles-ci ne soient pas considérées en données manquantes (ce qui n'aurait pas de sens), il faut les filtrer.
Le filtre avec le 1er du mois suivant était pensé en se disant que les saisies du mois n devaient être faites au mois n+1, mais en effet, cela soulève quelques problèmes: (i) pour le mois de décembre je n'y avais pas pensé, la complétion se faisant sur les campagnes usuelles, mais dans l'absolu oui, ça pourrait poser problème, (ii) si des saisies sont faites avant le 1er du mois suivant, elle n'apparaissent pas avant le mois suivant, c'est gênant...
Maintenant, la date attribuée aux campagnes 'complétées' est celle du 25 du mois, elles apparaîtront donc dès le 25 et seront considérées comme données manquantes à partir de cette date.
