### ISSUE TITLE
Ajouter un onglet Bilans départementaux

### ISSUE THREAD

**Issue by OFB-IdF** [richaben/PRR_ONDE#3]
Décliner les graphiques du bilan régional par département et les regrouper dans un onglet dédié

**Comment by richaben** [comment]
Pas d'affichage de graph pour le 94 (vu sur la page Idf) <img width="1008" alt="image" src="https://github.com/richaben/PRR_ONDE/assets/26381994/848f7a2b-240f-4ad0-8c8a-4dc0bd94e24d">

**Comment by OFB-IdF** [comment]
Oui, car aucune des deux stations n'est en assec, donc il n'y a rien à représenter. A voir si, dans ce genre de cas, on remplace le graphe vide par un message.
Pour le moment, je pense laisser en l'état.

**Comment by richaben** [comment]
Pour l'onglet bilan régional, on peut surement enlever les départements sur le premier graphique de conditions d'écoulement. Et en faire un sur l'ensemble de la région. cf. PR https://github.com/richaben/PRR_ONDE/pull/18
