### ISSUE TITLE
Déclinaison départementale ne couvre pas tous les départements

### ISSUE THREAD

**Issue by OFB-NA** [richaben/PRR_ONDE#30]
Bonjour, 
La déclinaison départementale est une évolution très utile : mais en NA les onglets ne sont générés que pour 5 départements parmi les 12.
Avez-vous une idée d'où ça peut venir ? 
(j'ai tenté la mise à jour du code mais elle n'a pas l'air d'aboutir).
Merci  beaucoup !

**Comment by CedricMondy** [comment]
Oui, nous avons eu quelques petits soucis pour la mise à jour, on va revenir vers vous pour vous expliquer la procédure.
Pour ton problème, je me demande si ce n'est tout simplement pas que les départements 'manquants' n'ont pas encore fait la dernière campagne usuelle alors que les autres l'ont fait...
Il faudrait voir pour éventuellement changer la logique ici...

**Comment by CedricMondy** [comment]
Une proposition de modification du code (#47) est en cours de test et pourrait permettre de résoudre le problème soulevé ici
