### ISSUE TITLE
Problème affichage de l'ensemble des bilans départementaux

### ISSUE THREAD

**Issue by OFB-BFC** [richaben/PRR_ONDE#32]
Bonjour,
je viens de réussir visiblement à réinstaller le dépôt régional et la page internet régionale pour la DR BFC.
Cependant il me manque 4 bilans départementaux (je n'en vois que la moitié).
Est-ce une erreur de manip de ma part ?
J'ai pourtant bien rempli les 8 départements entre guillemets...
Merci par avance pour votre retour !
Caroline Le Goff

**Comment by CedricMondy** [comment]
Il y a probablement un petit point à changer sur comment est géré cet onglet, mais je pense que, en l'état c'est normal. Les départements n'apparaissant pas doivent être ceux qui n'ont pas encore saisi les données pour les campagnes usuelles de 2023. Dès qu'ils auront saisi, leur onglet apparaitra (même problème relevé par NA ici: #30 )

Nous allons essayer de voir comment on peut changer le comportement pour que les départements soient toujours visibles dans cet onglet.

**Comment by CedricMondy** [comment]
Une proposition de modification du code (#47) est en cours de test et pourrait permettre de résoudre le problème soulevé ici
