### ISSUE TITLE
Ne pas afficher des campagnes usuelles différentes sur la même carte de l'onglet campagnes

### ISSUE THREAD

**Issue by Josefine57** [richaben/PRR_ONDE#33]
Bonjour,

Serait-il possible, si ça semble pertinent pour tous, de n'afficher sur la carte de l'onglet campagnes, que les campagnes usuelles du même mois.  Comme les SD ne remontent pas leurs observations en même temps, en début de mois, sur la  carte régionale, les résultats de 2 campagnes usuelles peuvent se côtoyer ce qui peut induire en erreur visuellement sur la situation si on ne prend pas le temps d'interroger les observations par département.

Sinon j'en profite pour informer que la réinstallation  semble être OK pour moi aussi,  merci pour le tuto!

**Comment by OFB-IdF** [comment]
Il me semble aussi que les règles d'affichage pour cette carte doivent être modifiées. Il faudrait que l'on en discute et valide cela collectivement, y compris avec Céline. Une proposition pourrait être d'utiliser la dernière campagne en dehors de la période du suivi usuel et de n'utiliser que les campagnes usuelles pendant la période de suivi.

**Comment by CedricMondy** [comment]
une proposition de modification de l'appli (#47) est en cours d'évaluation et devrait permettre de corriger cela
