### ISSUE TITLE
problème affichage typologie départementale onglet campagnes

### ISSUE THREAD

**Issue by Josefine57** [richaben/PRR_ONDE#34]
Bonjour,

Il me semble que la typologie départementale "écoulement visible faible" et "écoulement visible acceptable" n'apparaissent pas en affichage sur la carte quand on clique sur typologie départementale, l'affichage reste en typologie nationale

**Comment by OFB-IdF** [comment]
Effectivement, il semblerait que la couleur des points ne change pas alors que pour les popups c'est bon. Je vais essayer de regarder ça

**Comment by richaben** [comment]
Merci @Josefine57 👍 
C'est corrigé ! (cf. PR https://github.com/richaben/PRR_ONDE/pull/38)
