### ISSUE TITLE
Liens vers les tableaux de bord de chacune des régions

### ISSUE THREAD

**Issue by PascalIrz** [richaben/PRR_ONDE#44]
Suggestion : ajouter un onglet avec les liens vers les tableaux de bord de chacune des régions, voire une carte de France cliquable. Particulièrement intéressant sur les bassins qui ont le mauvais goût de ne pas suivre le découpage régional.

**Comment by CedricMondy** [comment]
Ce ne sont pas les tableaux de bord mais les dépôts sont listés ici: https://github.com/richaben/PRR_ONDE/forks

**Comment by PascalIrz** [comment]
> Ce ne sont pas les tableaux de bord mais les dépôts sont listés ici: https://github.com/richaben/PRR_ONDE/forks

Merci @CedricMondy, c'est effectivement utile pour les développeurs. En fait je pensais plutôt aux utilisateurs qui seraient intéressés par un périmètre recoupant plusieurs régions. Il serait utile de leur permettre de naviguer entre les tableaux de bord des régions concernées.
