### ISSUE TITLE
Problème d'affichage des "écoulements visibles faibles" sur la carte

### ISSUE THREAD

**Issue by OFB-NA** [richaben/PRR_ONDE#46]
Bonjour, 
Je ne suis plus sûre que l'on ait déjà échangé sur ce problème :

Sur l'onglet "Campagne", lorsqu'on sélectionne la "typologie départementale", les résultats de la dernière campagne n'illustrent que les 3 modalités nationales et pas les 4 départementales : les stations en "écoulement visible faible" apparaissent en bleu foncé et non en bleu clair.
Dans le détail de chaque station en revanche, on retrouve bien l'information.

Serait-il possible d'afficher cette information sur la carte?

Merci d'avance,

Emilie

**Comment by CedricMondy** [comment]
Le problème a déjà été signalé (#34) et normalement résolu, fait la mise-à-jour de ton dépôt et ça devrait être bon ;-)

**Comment by OFB-NA** [comment]
Je confirme la résolution du problème avec la mise à jour. Désolée pour la question inutile et merci pour les modifications.

**Comment by CedricMondy** [comment]
De rien ! ;-)
