### ISSUE TITLE
Masquer les pays voisins

### ISSUE THREAD

**Issue by broussel59** [richaben/PRR_ONDE#5]
Pour les HdF est-il possible de faire un masque sur les régions voisines, mais aussi sur la Belgique?

**Comment by OFB-IdF** [comment]
Oui, c'est prévu. Il faut que je retravaille le masque crée pour le moment à partir de la couche administrative métropolitaine.

**Comment by richaben** [comment]
Résolu. cf. la PR https://github.com/richaben/PRR_ONDE/pull/9
