### ISSUE TITLE
Graphique bilan départemental - cas des années (très) pluvieuses

### ISSUE THREAD

**Issue by PascalIrz** [richaben/PRR_ONDE#50]
Les années où il n'y a eu aucun assec sur le département sont omises du graphique. Bizarrement, c'est le cas du Finistère :

![image](https://github.com/richaben/PRR_ONDE/assets/20923555/2a8de3ec-aec6-49e1-99f4-efd735311516)

Ce qui tend à donner une fausse image de la "normale".

=> suggestion de faire figurer toutes les années.

**Comment by CedricMondy** [comment]
corrigé par #68

**Comment by OFB-IdF** [comment]
tiens, le problème n'est pas complètement corrigé...
![image](https://github.com/richaben/PRR_ONDE/assets/128606748/b064cdb2-1870-4660-a0fe-ce04de2784e0)

**Comment by CedricMondy** [comment]
j'ai changé la geom (geom_bar -> geom_col) et fixé la largeur des colonnes, le graphique est correct cette fois
![image](https://github.com/richaben/PRR_ONDE/assets/34371311/d186608b-7502-4f8b-be4b-e4a7b29e736b)

Ce qui est marrant c'est que en local, les graphiques étaient corrects chez moi...

**Comment by PascalIrz** [comment]
C'est parfait, merci !

**Comment by CedricMondy** [comment]
corrigé par #69
