### ISSUE TITLE
Problème de page web trop volumineuse

### ISSUE THREAD

**Issue by OFB-IdF** [richaben/PRR_ONDE#7]
Pour les grandes régions (e.g. NA), la page html générée dépasse la taille limite acceptée par Github pour les fichiers individuels (100Mo).

Pistes possibles: 
- optimiser la page web pour l'alléger (à préférer)
-  utiliser le système de stockage de gros fichiers (github LFS)

![image](https://github.com/richaben/PRR_ONDE/assets/128606748/ff6f8bf1-813b-468a-beb8-2005ad2d74e3)

**Comment by OFB-IdF** [comment]
J'ai fait des essais en enregistrant les graphiques des popups dans des fichiers indépendants et ça a l'air de résoudre le problème (PR #12 ), la page html en elle-même étant largement réduite en taille. Voir la page de test NA: https://cedricmondy.github.io/PRR_ONDE/ 
Par contre, cela suppose de versionner un grand nombre de fichiers images, à voir si cela ne posera pas de problèmes par la suite (problème en partie lié avec la mise à jour systématique Issue #13 )

**Comment by antonio-andrade** [comment]
L'utilisation de données compressées est-elle possible / opportune ?

**Comment by OFB-IdF** [comment]
En l'état de mes connaissances en html, je ne vois pas comment faire...
