### ISSUE TITLE
Réduire temps de traitements

### ISSUE THREAD

**Issue by OFB-IdF** [richaben/PRR_ONDE#8]
Pour Occitanie, le temps de traitement est trop long et dépasse les limites autorisées du temps maximal par job. 

Les traitements doivent être optimisés pour essayer de rendre cela plus rapide, il faut chercher les étapes qui sont les plus gourmandes en ressources et voir comment réduire ces demandes.

![image](https://github.com/richaben/PRR_ONDE/assets/128606748/f861b0bd-94f9-42f5-b691-547cf29c428b)

**Comment by OFB-IdF** [comment]
Apparemment, au déploiement automatique de la page ce matin, le prolème ne s'est pas présenté et le déploiement s'est fait comme il faut...

**Comment by richaben** [comment]
Oui, c'est hyper variable 
![image](https://github.com/richaben/PRR_ONDE/assets/26381994/63b56efe-fc6c-44c9-9cd3-b55c980424bc)

**Comment by OFB-IdF** [comment]
on va fermer l'issue en restant vigilant sur ce problème si cela se reproduit
